export const movie = [
  {
    movie_aid: 1,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 18,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "top2.webp",
    movie_is_active: true,
  },
  {
    movie_aid: 19,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "top3.webp",
    movie_is_active: true,
  },
  {
    movie_aid: 20,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 21,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 22,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 23,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 24,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "International",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 2,
    movie_title: "Scary Movie",
    movie_year: "2000",
    movie_duration: "1hr 28mins",
    movie_category: "International",
    movie_genre: "Horror, Comedy",
    movie_summary:
      "A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.",
    movie_cast: "Anna FarisJon, AbrahamsMarlon, Wayans",
    movie_rating: "R",
    movie_image: "scary.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 3,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "Action",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 6,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "Action",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 7,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "Action",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 8,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "Action",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 9,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "Action",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 10,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "Action",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 11,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "Action",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 4,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 12,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 13,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 14,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 15,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 16,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 17,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 5,
    movie_title: "White Chicks",
    movie_year: "2004",
    movie_duration: "1hr 49mins",
    movie_category: "KDrama",
    movie_genre: "Crime, Comedy",
    movie_summary:
      "Two disgraced FBI agents go way undercover in an effort to protect hotel heiresses the Wilson sisters from a kidnapping plot.",
    movie_cast: "Marlon WayansShawn WayansBusy Philipps",
    movie_rating: "R+18",
    movie_image: "white.jfif",
    movie_is_active: true,
  },
  {
    movie_aid: 24,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "Anime",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 25,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "Anime",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 26,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "Anime",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 27,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "Anime",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 28,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "Anime",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 29,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "Anime",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 30,
    movie_title: "Slamdunk",
    movie_year: "2031",
    movie_duration: "1hr 45mins",
    movie_category: "Anime",
    movie_genre: "Anime",
    movie_summary:
      "Follows 17-year-old Ryota Miyagi, who struggles to accomplish his late elder brother's dream of becoming a basketball star.",
    movie_cast: "afsghjgs",
    movie_rating: "+18",
    movie_image: "m-14.jpg",
    movie_is_active: true,
  },
];
